input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["entity-counts"]
    group_id => "logstash-entity-counts"
    auto_offset_reset => "earliest"
    codec => json
  }
}

filter {
  mutate {
    convert => {
      "count" => "integer"
    }
  }

  date {
    match => ["trigger_at", "ISO8601", "yyyy-MM-dd HH:mm:ss.SSS"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "entity-counts-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
